### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by celka** [commadelimited/autoComplete.js#1]
Hy.
Is there an option to not to pass to the link, insted just use, store the selected list in a variable?

**Comment by commadelimited** [comment]
celka...

Not sure what you mean. Could you give me an example?

**Comment by celka** [comment]
http://andymatthews.net/code/autocomplete/
In this example page
write example Alabama
then click to Alabama, it tries to open the following URL:
http://andymatthews.net/code/autocomplete/testing.cfm?term=Alabama

As I read the docs usage is:
$("#searchField").autocomplete({
    target: $('#suggestions'), // the listview to receive results
    source: 'data.cfc?method=search&returnformat=json', // URL return JSON data
    link: 'testing.cfm?term=', // link to be attached to each result
    minLength: 0 // minimum length of search string
});
so I have to add a link tag and it will loads that page, but what if I just want the selected list's content and do someting with that and after make a page load manually.(ex. a callback function which is called(and the choosen one passed in argument) when user chooses a valu from the list).
Hope you understand:)

**Comment by commadelimited** [comment]
Are you asking for a callback function to run instead of the link option? It sounds like you want something like this:

```
$("#searchField").autocomplete({
     target: $('#suggestions'), // the listview to receive results
     source: 'data.cfc?method=search&returnformat=json', // URL return JSON data
     callback: function(term){
          // do something here
     }
     minLength: 0
});
```

**Comment by celka** [comment]
Yes, I want this feature:)

**Comment by commadelimited** [comment]
Celka...

autoComplete 1.3 now has a callback function. Let me know if this does what you expect.

**Comment by celka** [comment]
Hello!
This is what I requested, thank you:)

**Comment by commadelimited** [comment]
Great. Glad to help out. That's going to be a good addition.
