### ISSUE TITLE
IE8 Support?

### ISSUE THREAD

**Issue by neilcoplin** [commadelimited/autoComplete.js#12]
In looking over the demo page at http://andymatthews.net/code/autocomplete/, it doesn't look like IE8 (Windows) is running the autocomplete at all.  I'd LOVE to be using this plugin for some projects at work, though sadly we're still required to use IE8...  I'm happy to help get it up to speed in IE8 though.  If you have any ideas as to why it may not be working in IE8, let me know such that I can start looking into it myself as well.  Thanks!

**Comment by commadelimited** [comment]
Neil...

Not sure why it's not working in IE8. Would you mind taking a look and seeing if there's any JavaScript errors being reported?

**Comment by neilcoplin** [comment]
There are not. :(  I set a breakpoint at the start of the page and started walking through the javascript executing, so at the very least it _is_ getting executed.  However breakpoints inside of the buildItems and handleInput functions never seemed to be reached when I was typing into the input field.  I'll try investigating further, but anything you find that could help as well, let me know.

**Comment by neilcoplin** [comment]
From what best I can tell, the input event isn't supported in IE prior to 9, which may be why the initial javascript gets run, but the event never gets triggered.

http://msdn.microsoft.com/en-us/library/ie/gg592978%28v=vs.85%29.aspx (if you hover over the IE logo, it says IE9)

In looking over the binding events for jQuery UI's autocomplete, it looks like they're primarily using the keydown event for the autocomplete.  So that could be attempted, but my preliminary tests haven't resulted much promise...

**Comment by neilcoplin** [comment]
It looks like changing the bind event from "input.autocomplete" to "keyup.autocomplete" fixes the issue in IE8, and it still resolves relatively well in other browsers.  You can perform your own testing of course.  Initial tests had failed due to a misconfiguration in my call of the script, but after I fixed those, it seems to perform fine with the one adjustment.

**Comment by RichardDalton** [comment]
@neilcoplin Did you not find that the call to _.filter()_ in the _handleInput_ function threw an error in IE8? This function is not supported in any IE before IE9. 

Easiest way to handle this would be to add a shim such as the one under compatibility here - https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Array/filter

**Comment by neilcoplin** [comment]
I was using the widget with the ajax source option, so I never hit that section of the code.  Though yes, I believe that is correct that the .filter() isn't supported in IE8.

**Comment by RichardDalton** [comment]
Thought that might be the case.

**Comment by commadelimited** [comment]
This should be resolved in 1.4, out later today.
