### ISSUE TITLE
Source callback support is missing

### ISSUE THREAD

**Issue by bernharduw** [commadelimited/autoComplete.js#14]
The pull request https://github.com/commadelimited/autoComplete.js/pull/5 is missing in V1.3. Could you add this again please?

Sorry for not issuing a pull request - I added this in line 76:

```
...
                buildItems($this, data, settings);
            } else if ($.isFunction(settings.source)) {
                settings.source(text, function(data) {
                    buildItems($this, data, settings);
                });
            } else {
...
```

**Comment by commadelimited** [comment]
bernharduw...

Could you provide a reason for allowing this versus the callback function already provided in the api?

**Comment by bernharduw** [comment]
The source callback is fired before building the list.

The new callback function in the api is fired when I click a link in the list.

I am using the source callback to build a custom url from the query (I cannot provide the simple url format that you require, so I had to customize the ajax request).

Cheers, Bernhard

**Comment by commadelimited** [comment]
Ahhh. That makes perfect sense. I'm going to be adding unit tests for all my plugins over the next week or two. When I get to autoComplete I'll add this functionality back in.

**Comment by commadelimited** [comment]
This will be in 1.4 which should come out later today.
