### ISSUE TITLE
Feature: Stop outstanding ajax when a new one is made

### ISSUE THREAD

**Issue by neilcoplin** [commadelimited/autoComplete.js#22]
Not sure if you'd like this to be added back to the main project, but another modification I made to my local copy was adding the ability for the developer to have outstanding ajax requests to be stopped when a new request is made.  For a while I had issues with a slow results page (which fortunately is now fixed) that would sometimes make it so the last call made wasn't always the last one returned.  This resulted in the most refined results getting overwritten by a previous search.

The code is written such that if multiple autocomplete widgets are present on a page, it only stops the outstanding requests for the widget you are working with, if multiple widgets have outstanding requests.

Anyway, lemme know if you'd like me to post the code.

**Comment by commadelimited** [comment]
If you've already got it running, then by all means post it please. I'm pausing the rewrite to jQuery UI Widget Factory so I can import some of these pull requests. It'll be easier to do it that way rather than trying to reconcile a totally different architecture.

**Comment by commadelimited** [comment]
This will show up in 1.4, out later today.
