### ISSUE TITLE
"href" attribute of link is "#" in callback

### ISSUE THREAD

**Issue by mezcala** [commadelimited/autoComplete.js#25]
Hi,

I noticed something weird with autoComplete (v 1.4.1) and Safari on iOS 5.1 : 

When I try to get the "href" value of clicked item in callback, I get "#". But it works perfectly fine with desktop browsers. Any idea ? Am I missing something ?

``` javascript
myInput.autocomplete({
    target: $('#suggestions'),
    source: function(request, response){
        // api call returning JSON
        response(returned_json);
    },
    callback: function (e) {
        var link = $(e.currentTarget);
        var href = link.attr('href'); // returns "#"
    },
    link: '?id=',
    minLength: 3
});
```

**Comment by commadelimited** [comment]
@whoisthecoon, thanks for providing code, but do you perhaps have a link online I can view?

**Comment by mezcala** [comment]
Unfortunately, I can't put my project online for confidentiality reasons… Do you have an idea of what could cause the problem ? Cause I don't mind trying to debug it myself and post the results here, but I don't have any clue...

**Comment by mezcala** [comment]
Hi,

I couldn't find the problem. I don't have enough time so I did it differently : I passed my data via the data() function of JQuery in the link element (I had to modify jqautocomplete for this, but I had to use 1.4). By the way, I will suggest the use of data() in another thread.

**Comment by MatheusRRO** [comment]
I found one "solution" for this issue.
Just change lines 33 and 35, putting value or value.value inside name attribute, instead of concatenate it with href. And then take the value from there.

And to be more weird, this problem only happens when my page is accessed from a mobile device.

**Comment by cardinal27513** [comment]
This is the same problem that I'm trying to figure out.. it is not just an issue on Safari. I use Chrome on iOS 5.1. The same problem... Getting just "#" from the href.

**Comment by cardinal27513** [comment]
Hi Andy,
  Figured it out that the problem only happends with jqm-1.1.0 and for  jqm-1.1.1, it works as expected.
  Here is the jsfiddle link to show the issue.. please let me know if you can get to the link or not.. 

http://jsfiddle.net/cardinal27513/yjF2f/

  We are using jqm-1.1.0 and wont be able to upgrade for some time since we are hitting different issues in jqm-1.1.1 itself.

  Really appreciate, if you can help to see if the issue can be addressed for jqm-1.1.0.

ming

**Comment by cardinal27513** [comment]
Tried out to use 'Data-autocomplete' instead and it works in jqm-1.1.0 so .. will stay away from href for now.
thanks.

**Comment by commadelimited** [comment]
Great. I think that the `data-autocomplete` property will solve a lot of issues.
