### ISSUE TITLE
target listviev not being cleared from search box “clear button” 

### ISSUE THREAD

**Issue by cardinal27513** [commadelimited/autoComplete.js#26]
Just attached autocomplete to a search input box.
When I clear the search text manually, the target listviev is cleared as expected but if clicking  the ‘clear button’ from the search box,  the list target is not cleared?

Ming

**Comment by commadelimited** [comment]
@cardinal27513, currently autocomplete only supports the text input box. I haven't yet written against search input boxes.

**Comment by commadelimited** [comment]
Believe it or not this is harder than it appears. There's no "clear" event being fired by either the browser or jQuery Mobile. Working on it though.

**Comment by cardinal27513** [comment]
thanks for looking into it... Everything works except this little "clear" event. :-(

**Comment by commadelimited** [comment]
Can you please view the demo and tell me if that works for you?

http://andymatthews.net/code/autocomplete/search.html

**Comment by cardinal27513** [comment]
yes. that works for me.. many thanks.

**Comment by cardinal27513** [comment]
Also will it be a 'clear' event or 'change' event fired?  
I'm trying to integrate auto-complete with 'Backbone.ModelBinder'. From what I can tell, ModelBinder only registers with 'change' event not 'clear' event.

**Comment by commadelimited** [comment]
Ming Chan...

Take a look at this line of code:
https://github.com/commadelimited/autoComplete.js/blob/master/jqm.autoComple
te-1.4.2.js#L61

The "targetCleared.autocomplete" event is fired when the clearTarget method
is called. You should be able to listen for that event.

andy

**Comment by cardinal27513** [comment]
thanks!
ming
