### ISSUE TITLE
Click callback should have "this" be the target element

### ISSUE THREAD

**Issue by IceCreamYou** [commadelimited/autoComplete.js#27]
Instead of settings.callback(e), it would be nice to have settings.callback.call(this, e)

https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Function/call

**Comment by ghost** [comment]
A work around for this since you're using jquery already is to define the callback like so:
callback: $.proxy(yourCallBackMethod, $(autocompleteElement)),
