### ISSUE TITLE
listview item template

### ISSUE THREAD

**Issue by teddyber** [commadelimited/autoComplete.js#28]
Hello,

this is a feature request.
I'd love to benefit from this plugin to make a "search" feature.
I have "complex" listview items representing objects (let's say a wine) with different attributes (name, producer, grape type, etc.)
I'd like 
- the search being done remotely (server side) on different attributes => this I can do
- the results to be more than just listview items with value and label but more complex items with .ui-li-count, .ui-li-aside elements

I think a 'template' parameter could do the trick with a simple tokens to replace with values from the json data.
what do you think?

**Comment by teddyber** [comment]
oops, that's a duplicate of #6
really sorry

**Comment by commadelimited** [comment]
teddybear...great idea. I've asked another developer for some input on some of these elements and that's one of them that could be very useful.
