### ISSUE TITLE
Use jquery.data() to pass data to the clickable link element.

### ISSUE THREAD

**Issue by mezcala** [commadelimited/autoComplete.js#30]
Hi,

I think it would be usefull to be able to pass some data to the link element.  Fill data() with the object 'value' used in the loop of the `buildItems` function in order to use it in the callback. I tried with the 1.4 version of jqmautocomplete, but you used a different way to fill the <ul> in 1.4.1.

Here's what I did  (jqm.autocomplete-1.4.js line 35): 

``` javascript
var lnk = $('<a href="' + settings.link + encodeURIComponent(value.value) + '" data-transition="' + settings.transition + '">' + value.label + '</a>')
               .data('item_data', value)
              .appendTo(li);
```

Is this a good idea ? What do you think ?

**Comment by commadelimited** [comment]
Hey @whoisthecoon, have you tried 1.5 yet?

**Comment by mezcala** [comment]
@commadelimited, yeah, I just did, and it seems to work great with the data-autocomplete attribute, thanks !

**Comment by commadelimited** [comment]
Excellent.
