### ISSUE TITLE
Adding Jasmine specs

### ISSUE THREAD

**Issue by apeckham** [commadelimited/autoComplete.js#32]
Andy, in [PR #18](https://github.com/commadelimited/autoComplete.js/pull/18#issuecomment-6342175) you expressed interest in adding specs. I agree that specs will help out as the library is improved little by little, and the specs will help prevent regressions.

Is this still a goal of yours? Are you open to a pull request with Jasmine specs?

**Comment by commadelimited** [comment]
Aaron...if this is something you're interested in looking at, I'd LOVE to have unit tests for this thing. As other people add functionality it's becoming harder to manage submissions without having a solid foundation for checking work.
