### ISSUE TITLE
List rendering as raw bulleted list

### ISSUE THREAD

**Issue by jaynathan79** [commadelimited/autoComplete.js#33]
Hi Andy, I'm having success getting autocomplete to respond and bringing back results from a URL, but when I bind them to my empty &lt;ul&gt; (like in your remote object example), the list renders as a plain old bulleted list as opposed to a styled jquery mobile listview. 

Have you ever run across this problem before? I've racked my brain trying to understand why this would happen... Thanks for any insights/ideas.

**Comment by commadelimited** [comment]
@jaynathan79, introspect the list in your example with Firebug or Chrome Dev Tools. The opening UL tag should look something like this:

```
<ul data-role="listview" data-inset="true" data-theme="c" data-dividertheme="f" class="ui-listview ui-listview-inset ui-corner-all ui-shadow">
```

If it doesn't then my guess is that the list isn't being init-ed properly. Do you have code online somewhere?
