### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kurteknikk** [commadelimited/autoComplete.js#34]
Hi,

First of all very nice widget, very close to what i was looking for, i had a couple of ideas if you're interested:

1) The autocomplete should be used in forms so usually we expect to have: <label> <input>
2) You can setup options as attributes such as: <input data-role="autocomplete" data-autocomplete_src="data.php?get=1"

What do you think ?

**Comment by fathergorry** [comment]
agree

**Comment by commadelimited** [comment]
Yes. Eventually I'd like to package it up to be used more like other widgets in jQuery Mobile. This might be a moot point as I think the jQuery Mobile core team is working on it's own autocomplete widget.
