### ISSUE TITLE
Special characters in search string

### ISSUE THREAD

**Issue by ifox** [commadelimited/autoComplete.js#37]
Hello,

i use your autoComplete.js for a list of IT competences. One is C/C++.
If I type C++ i get this error on my console : 

_Uncaught SyntaxError: Invalid regular expression: /c++/: Nothing to repeat 
jqm.autoComplete-1.4.3-min.js:10_

I guess an encodeURIComponent would make it.

Great plugin by the way :)

iFox

**Comment by commadelimited** [comment]
Thanks for the suggestion @ifox. Would you be interested in submitting a pull request with that change?

**Comment by commadelimited** [comment]
@ifox, this should be resolved now. Can you confirm?

I've also updated the demos to use programming languages to make this fix easier to test.
