### ISSUE TITLE
Add Input Parameters To A Post Request

### ISSUE THREAD

**Issue by npl77** [commadelimited/autoComplete.js#40]
Is there a way available to add input parameters to an ajax service call?
Here is a sample c# service:
 [OperationContract]
        [WebInvoke(Method = "POST", RequestFormat = WebMessageFormat.Json, BodyStyle = WebMessageBodyStyle.WrappedRequest, ResponseFormat = WebMessageFormat.Json)]
        public List<string> GetStates(string y)
        {
            List<string> x= GetData(y);
            return x;

```
    }
```

Client call:
//WHERE DO I PUT INPUT PARAMETERS??

   $("#searchBox").autocomplete({
                method: 'POST',
                target: $('#suggestions'),
                source: "ClientService.svc/REST/GetStates",
                link: 'target.html?term=',
                minLength: 1

```
        });
```

**Comment by blasky** [comment]
Am I reading this correctly that there is no way to specify additional input parameters that are required for the execution of an autocomplete call?

I have a pretty standard looking manufacturer and brand scenario where the user may specify a manufacturer and if so, the results for the brand autocomplete should be limited to the brands within that manufacturer's brand space. But this can't happen without the ability to pass the manufacturer id along with the search term.

Not currently possible?

**Comment by blasky** [comment]
I just developed a work around using the onLoading method hook to modify the source property at run time based on  current additional field values in my model. All is good. Although it would be nice to have standard support for cases like this. Thanks.

**Comment by commadelimited** [comment]
@blasky would you mind posting your code? Perhaps your fix could be implemented.
