### ISSUE TITLE
Clear ListView when focus is lost

### ISSUE THREAD

**Issue by seguinj** [commadelimited/autoComplete.js#44]
What would be the best way to clear the listview when focus is lost?

I suppose I could set an on click on the parent div and detect if the target is not 'ui-link-inherit' and then run an autocomplete('clear') method on all my input fields? This doesn't seem very efficient however. 

Any thoughts?

**Comment by commadelimited** [comment]
You want to clear the listview when the input field loses focus? That event would fire every time you tried to select an item from the listview. What's your thought process on why you'd want to do that? What are you trying to solve?

**Comment by seguinj** [comment]
Here's what I'm trying to solve. 

I have a form with several fields that allow the user to have his/her text autocompleted. If a user begins to enter text in an input field that has autocomplete and no results are selected, the autocomplete listview remains on screen. Even if the user scrolls up or down or gives focus to another input field.

**Comment by commadelimited** [comment]
There is a clear event that you could fire when needed:

https://github.com/commadelimited/autoComplete.js#clear

I'd say that you could add a blur event to the autocomplete input field that triggers the clear event.

**Comment by seguinj** [comment]
Can you provide an example on how you would do this?

Here's what I've tried so far...
I have an On('blur') event which is clearing the autocomplete list when my input field loses focus. When a user actually does click on an autocomplete list item, the blur event overrides the callback to display the listview target in the input text value. What's happening is that no matter what the user does, the blur event is not allowing the autocomplete text to be added in the input field.
