### ISSUE TITLE
only works once

### ISSUE THREAD

**Issue by leopittoni** [commadelimited/autoComplete.js#45]
Hi!

Auto complete is working, but after clicking the result linked to the same page and than back to the search page, automatch isn't working anymore.

$("#search_input").autocomplete({
                target: $('#suggestions'),
                source: autocompleteData,
                link: 'add_date.php?date=<?php echo($date) ?>&id=',
                minLength: 1
            });

if (ISSET($_GET["id"])){

some code here...

header("location:add_date.php?date=$datum");
die;

}

**Comment by zabby** [comment]
have the same problem here - any suggestions?

**Comment by ytsurk** [comment]
same for me.
the issue was, that $(document).ready() seems to be too early loading..,
as i use it in a jqm-popup, i bound initialisation to popupafteropen.
the first time it worked - because i initialized it with an array, after fetching the data ..

i tried a lot of other things, like autocomplete('destroy', fn(){}), autocomplete('update', fn(){}) etc.

**Comment by leopittoni** [comment]
Any solution?

**Comment by ytsurk** [comment]
yes - initializing it later .. try to use a timeout ..
did not really debug the source. it was not binding the events .. - init got called ..

**Comment by leopittoni** [comment]
How do you managed to initialize it correctly?
Can you pleas post a code example?

Thanks!

**Comment by ytsurk** [comment]
do something like

``` javascript
var tOut = window.setTimeout(function(){
  $('.search-input').autocomplete({ options .. });
}, 900);
```

play with the time - could probably be less ..

**Comment by leopittoni** [comment]
$("#searchpage").bind("pageshow", function(e) {

```
        $("#search_input").focus();

        window.setTimeout(function(){
        $("#search_input").autocomplete({
            target: $('#suggestions'),
            source: 'sql_search.php?id=<?php echo($id) ?>',
            link: 'add_date.php?id=<?php echo($id) ?>&userid=',
            minLength: 1
        });

        }, 900);    
    });
```

does also work onyl once. Any idea?

**Comment by ytsurk** [comment]
no sorry .. as I said, i'm using it in a popUp, like

``` javascript
$('.popSearch').bind({
    popupafteropen: function(event,ui) {
      $('.search-term').autocomplete({
        target: $('.auto-suggestions'),
        source: searchAuto,
        callback: function(e) {
          var $a = $(e.currentTarget);
          var aTxt = $a.text();
          if(aTxt.indexOf('Photo-#: ') == 0){
            $('.ui-checkbox-off').addClass('ui-checkbox-on').removeClass('ui-checkbox-off');
            $('.ui-icon-checkbox-off').addClass('ui-icon-checkbox-on').removeClass('ui-icon-checkbox-off');
          } else {
            $('.ui-checkbox-on').addClass('ui-checkbox-off').removeClass('ui-checkbox-on');
            $('.ui-icon-checkbox-on').addClass('ui-icon-checkbox-off').removeClass('ui-icon-checkbox-on');
          }
          $('.search-term').val($a.text().replace('Titel: ', '').replace('Photo-#: ', ''));
          $('.search-term').autocomplete('clear');
        },
        matchFromStart: false,
        maxItems: 6,
        minLength: 3
      });
    }
  });
```

thus not with an ajax request but an array ..,
maybe try to fetch your JSON before and pass it as source.

autocomplete behaves differently for each source type

**Comment by ytsurk** [comment]
just another thought - maybe it could help to destroy the autocomplete on pagebeforehide,
as i guess it having somehow old data from the old hidden (or in my case) removed page from DOM

``` javascript
$(".searchpage").bind("pagebeforehide", function(e) {
  $(".search_input").autocomplete('destroy'); 
});
```

**Comment by namlook** [comment]
I had the same issue and solve it: use class instead of id and remove the target on-pagebeforeload.

Here's my code:

``` javascript
$(document).on("pagebeforeload", function(e) {
    $("#search-suggestions").remove();
});

$(document).on("pageshow", function(e) {
    $(".my-search").autocomplete({
        method: 'GET',
        minLength: 1,
        target: $('#search-suggestions'), // the listview to receive results
       source: ['foo', 'bar', 'baz', 'erf', 'barista']
   });
});
```

Try to avoid using ids with jquery-mobile. JQM is adding multiple pages in the DOM so, if you use ids, you will get some conflicts. Use class instead when you can.

**Comment by leopittoni** [comment]
This worked for me! Thanks!

**Comment by ytsurk** [comment]
sorry - forgot that to mention explicitly .., and added ids for the short examples (just changed)
