### ISSUE TITLE
Autocomplete does not send Ajax requests

### ISSUE THREAD

**Issue by cb1000** [commadelimited/autoComplete.js#47]
Hi guys,

good job - autocomplete is a great plugin!

I tried with several browsers and found some issues. You can reproduce them in your example http://andymatthews.net/code/autocomplete/ 
1. Desktop browsers (IE9/FF17):
After typing the first character (e.g. A) autocomplete finds some values. If you delete this character the list will be cleared (this does not happen in Chrome Mobile). By typing the character again autocomplete does not show any values.
2. Chrome Mobile:
The listview does not change by deleting characters, e.g. you are typing Alabama, the listview shows one result. If you delete the characters the listview will not be refreshed. You have to type a new character first.

Regards
Danny

**Comment by commadelimited** [comment]
I tested it in the most recent version of Chrome for iOS and it worked just fine.

I also tested it in IE9 on a VM and that worked fine too. So either it was fixed in a more current version than what you tested, or those browsers have been updated. Or both.

Looks like it's fixed now though. Yay!
