### ISSUE TITLE
a small fix for python-turbogears backend.

### ISSUE THREAD

**Issue by timucin** [commadelimited/autoComplete.js#49]
When I try to use this plugin with python-turbgears backend, my server side application do not permit me to return array as json. 
## Here is the error message:

 Module tg.controllers.decoratedcontroller:265 in _render_response         view

> >  'You may not expose with JSON a list return value because'
> > ## JsonEncodeError: You may not expose with JSON a list return value because it leaves your application open to CSRF attacks.

I can return json from server like this:

{data: [
    {
        value: "22",
        label: "Maine"
    },
    {
        value: "23",
        label: "Maryland"
    }
]
}

Jquery implementation of autocomplete is ok with this return data so I've look at the code and done a quick fix:

line 200 of jqm.autoComplete-1.5.0.js, I've changed 
                            buildItems($this, data, settings);
to
                            buildItems($this, data.data, settings);
and the new code looks like this:

```
                var ajax = {
                    type: settings.method,
                    data: {},
                    dataType: 'json',
                    beforeSend: function(jqXHR) {
                        if (settings.cancelRequests) {
                            if (openXHR[id]) {
                                // If we have an open XML HTTP Request for this autoComplete ID, abort it
                                openXHR[id].abort();
                            } else {
                            }
                            // Set this request to the open XML HTTP Request list for this ID
                            openXHR[id] = jqXHR;
                        }

                        if (settings.onLoading && settings.onLoadingFinished) {
                            settings.onLoading();
                        }

                        if (settings.loadingHtml) {
                            // Set a loading indicator as a temporary stop-gap to the response time issue
                            settings.target.html(settings.loadingHtml).listview('refresh');
                            settings.target.closest("fieldset").addClass("ui-search-active");
                        }
                    },
                    success: function(data) {
                        buildItems($this, data.data, settings);
                    },
                    complete: function () {
                        // Clear this ID's open XML HTTP Request from the list
                        if (settings.cancelRequests) {
                            openXHR[id] = null;
                        }
                        if (settings.onLoadingFinished) {
                            settings.onLoadingFinished();
                        }
                    }
```

Maybe there should be a optional parameter to use this autocomplete plugin for pythonistas like me. :)

**Comment by commadelimited** [comment]
I'd rather not start adding options for specific server side languages. It sounds like you were able to fix it for your use case though, and that makes me glad.
