### ISSUE TITLE
limit number of results items

### ISSUE THREAD

**Issue by davidfigueres** [commadelimited/autoComplete.js#50]
I did this little modification to limit the elements on proposal result lists.

var defaults = {
[...]
maxItems: 0 //all items
}

change this:
if ($.isArray(str)) {
str = str.join('');
}

for this:
if ($.isArray(str)) {
if(settings.maxItems > 0)
str.splice(settings.maxItems,str.length-settings.maxItems);
str = str.join('');
}

**Comment by commadelimited** [comment]
@mentuhotep, If you'd submit a pull request for this I'd be happy to review it.
