### ISSUE TITLE
IE 8 & 7 - issue when using callback

### ISSUE THREAD

**Issue by seguinj** [commadelimited/autoComplete.js#51]
I'm getting an error when testing in IE 8 and IE 7. See attached screenshot for actual error message when using IE Tester and opening up an IE 8 browser. 
![image001](https://f.cloud.github.com/assets/2645459/139971/8f27ed30-720c-11e2-8eac-0721e5818b54.png)

I'm getting the error on the following demo pages: http://andymatthews.net/code/autocomplete/callback.html and http://andymatthews.net/code/autocomplete/callback-plus.html.

**Comment by commadelimited** [comment]
I won't be supporting IE7, but if you can provide sample code I'd be happy to look at it in IE8.
