### ISSUE TITLE
A way to customize the content of <li>'s in the list

### ISSUE THREAD

**Issue by bjornbak** [commadelimited/autoComplete.js#6]
I have an autocomplete implemented with jQuery UI autocomplete on our desktop site.. I now working on a mobile version but would like not to introduce massive jQuery UI into it.. I found your alternative but is missing a couple of features.

I have a datasource that don't returns objects with value and label properties. It returns 5 properties which I use the decide what and how it is shown in the list. This I solve in jQuery UI by overridding _renderItem.

When an item is selected I access the 5 properties again and updates 3 different form fields with a "select" function. This select function resembles your callback but an ui object is passed to it containing the 5 properties. Unsure if and how I would be able to save and access those given a _renderItem function in your plugin. Could it be through the $(e.currentTarget) object?

My jQuery UI code from the desktop site:
        $('#destination').autocomplete({
            source: '<url to server>',
            minLength: 3,
            appendTo: '#autocomplete',
            cache: true,
            select: function( event, ui ) {
                if (ui.item.LID != null) {
                    console.log('LID:'+ui.item.LID);
                    $('#navn').val('');
                    $('#destination').val(ui.item.LN);
                    $('#regionId').val(ui.item.RID);
                    $('#lokalOmraadeId').val(ui.item.LID);
                }
                else if (ui.item.RID != null) {
                    console.log('RID:'+ui.item.RID);
                    $('#navn').val('');
                    $('#destination').val(ui.item.RN);
                    $('#regionId').val(ui.item.RID);
                    $('#lokalOmraadeId').val('');
                }
                else {
                    TOjQ('#navn').val(ui.item.FN);
                    TOjQ('#destination').val(ui.item.FN);
                    $('#regionId').val('23');
                    $('#lokalOmraadeId').val('');
                }

```
            return false;
        }
    }).data( "autocomplete" )._renderItem = function( ul, item ) {
        var text;
        if (item.LID != null) {
            text= '<span class="omraade">omraade</span>' + ' ' + item.LN + ' / ' + item.RN;
        }
        else if (item.RID != null) {
            text= '<span class="region">region</span>' + ' ' + item.RN;
        }
        else {
            text = '<span class=" + item.BN.toLowerCase() + '">' + item.BN + '</span>' + ' ' + item.FN + (item.ID != '' ? ', '+ item.BY : '');
        }

        return TOjQ( "<li></li>" )
            .data( "item.autocomplete", item )
            .append( '<a>' + text + '</a>' )
            .appendTo( ul );
    };
});
```

**Comment by commadelimited** [comment]
Bjornbak...

I'll consider this feature for next release.

**Comment by teddyber** [comment]
I'd say a template would help here.
maybe better : a callback function outputting an HTML String/DOM object from the json Element
