### ISSUE TITLE
Multiple autocomplete in one page

### ISSUE THREAD

**Issue by ChristianBcn** [commadelimited/autoComplete.js#60]
it's possible put 2 autocomplete in the same page? If it's possbile How I can I do? What I need change? thanks!!

**Comment by commadelimited** [comment]
I haven't tried it out. But there shouldn't be any reason why you couldn't. Have you tried it?

**Comment by ChristianBcn** [comment]
I fixed the problem :) thanks!

**Comment by commadelimited** [comment]
Excellent. Why not post some of your code here so that others can learn!
