### ISSUE TITLE
Can't load autoComplete.js: Uncaught TypeError: Object [object Object] has no method 'autocomplete'

### ISSUE THREAD

**Issue by ltpitt** [commadelimited/autoComplete.js#63]
Hello there!

I am trying to use autoComplete.js in some learning mini projects I'm building trying to understand how to program with jQuery Mobile.

I've decided to start with the callback example (http://andymatthews.net/code/autocomplete/callback.html) and I've simply copied it in an empy file and saved as html: works perfectly, of course.

So I give the code a go in one of those mini projects but if I have another page linking to a page containing the autocomplete function it stops working.

index.html ---link to --> autocomplete_page.html

I've tried various solutions but nothing seems to work.

It's surely a very silly answer but being a beginner I don't find this easy to achieve.

I've tried adding in the <head> section of index.html and the other html page this row (calling my separate js file):

<script type="text/javascript" src="js/inserimento_movimento.js"></script>

And in the file I've tried various solutions to run the code, all with bad results.

The best one, accordingly to info kindly given on the jquery mobile official forum should be:

<pre><code>
var data = ['C', 'Clojure', 'Java', 'Scala', 'Objective-C', 'C++', 'PHP', 'C#', '(Visual) Basic', 'Python', 'Perl', 'JavaScript'];

$(document).on("pageshow", ".mypageclass", function(e) {
console.log("Code running");
$(".searchField").autocomplete({
                                target: $('.suggestions'),
                                source: data,
                                minLength: 1,
                        });
                });
</pre></code>

Still no luck: the code is not executed.

If I open the console I see:

Uncaught TypeError: Object [object Object] has no method 'autocomplete' 

The code (both html and js) has been modified to try with ids or classes: same result.

If I reload the second page I get a perfectly working autocomplete.

What am I doing wrong? 

Forgive the newbie's question.

**Comment by commadelimited** [comment]
@ltpitt You said that the pages are nearly identical, and that autocomplete works on the second page. That means that autocomplete is being attached before it's fully loaded.

Here's a listing of the events that jQuery Mobile provides: http://api.jquerymobile.com/category/events/

I'd give pageload or pagechange a try. The problem with pageshow is that all of the elements have already been initialized on the page before that event fires.

**Comment by ltpitt** [comment]
Thanks a lot for helping me even if this is probably not really autocomple.js related!

I've tried all the events that looked to me right and then blindly all the events: no luck at all.

It either won't fire or throw the above error.

I've also found some good information here:

http://stackoverflow.com/questions/14468659/jquery-mobile-document-ready-vs-page-events

But it won't work anyway...

I am doing something really stupid but I can't get what :(

**Comment by commadelimited** [comment]
It might be helpful if you had a link with these two pages that I could look at.

**Comment by ltpitt** [comment]
Sure thing!

Excuse me if I didn't do it before...

http://pitto.homeip.net/core/

You need to choose the 1st link "Inserimento Movimento" and the autocomplete field is "Cognome".

Right now it's set on "pagechange".

Thanks a lot for your time.

ps
If you want you can also click on "Report B": this link redirects to your example page instead of the previous one suggested which is made by me.

**Comment by ltpitt** [comment]
Forgive the waste of time over my poor and novice skills...

I forgot to load autocomplete.js ALSO in the index.html

Sorry again and thanks for the good work and help!
