### ISSUE TITLE
Passing in additional parameters

### ISSUE THREAD

**Issue by gregh3269** [commadelimited/autoComplete.js#67]
Hello,

This is a great plugin, but it would be useful to add a data{} section so we can pass additional parameters:

After line #22 add  data: {}, ie

link: null,
data: {},
minLength: 0,
...

Change line #192
data: {}, 

 to 

data: settings.data,

Cheers Greg.

**Comment by commadelimited** [comment]
Greg. Good idea. Since you already know what needs to be adjusted, would you mind putting in a pull request for that?
