### ISSUE TITLE
Delay before firing ajax calls

### ISSUE THREAD

**Issue by bjornbak** [commadelimited/autoComplete.js#7]
If I set the minlength to 1 and writes "This is a test" your autocomplete fires 14 ajax calls.

jQuery UI's autocomplete operates with a delay to allow the user to finish the typing.. I would like to see this in your autocomplete too as the ajax calls are expensive on the mobile data connections..

Another thing is that jQuery UI's autocomplete cancels old ajax calls if a new one is fired. I guess this saves bandwidth too.

**Comment by commadelimited** [comment]
jQuery UI: https://github.com/jquery/jquery-ui/blob/master/ui/jquery.ui.autocomplete.js#L369
function: search, lines 339 - 366

**Comment by ydyu** [comment]
My fork at https://github.com/ydyu/autoComplete.js/ currently has a "delay" option, it may not be as neatly implemented as the jQuery UI, but seems very functional for my purposes. Anyone is welcome to try my fork and offer comments, perhaps we could work out a better implementation suitable for the upstream.
