### ISSUE TITLE
MySQL Example

### ISSUE THREAD

**Issue by dirtyrobinson** [commadelimited/autoComplete.js#71]
Would you happen to have an example of how I could use your autocomplete with a MySQL database?

**Comment by commadelimited** [comment]
@dirtyrobinson The `source` attribute should contain the URL to a page from which your data will be retrieved. That page could be a PHP page, a Rails or Django API endpoint, or a static file containing a JSON object. If you're not using "on page" data then it's up to you to perform the search against your MySQL database.
