### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by oshanz** [commadelimited/autoComplete.js#72]
it only search labels start from what i type. how can it change to even search from middle or end (%term%)

**Comment by commadelimited** [comment]
@oshanz Are you using "on page" data, or remote data? If it's remote, then you're responsible for performing the search and returning the data to the page. If it's "on page" data there's a parameter called `matchFromStart` which can be set to false to perform fuzzy matching (middle of the string searches).

**Comment by oshanz** [comment]
Thanks.
i wanted that 'matchFromStart' parameter.
nice.

**Comment by commadelimited** [comment]
Glad it's already there. Enjoy!
