### ISSUE TITLE
Question: Accessing value in callback

### ISSUE THREAD

**Issue by yashgt** [commadelimited/autoComplete.js#74]
Hi,

From a complex data source, I have constructed the {value, label}. The callback gets called when user chooses an item. In the callback, the label can be accessed as $a.text(). How can we access the value?

Thanks,
Yash

**Comment by powertronglobal** [comment]
I have the same question?

**Comment by yashgt** [comment]
http://andymatthews.net/code/autocomplete/callback-plus.html

Sounds like it might be what you're looking for. 

$("#searchField").autocomplete({
    target: $('#suggestions'),
    source: autocompleteData,
    callback: function(e) {
        var $a = $(e.currentTarget);
        $('#searchField').val( $a.data('autocomplete').value );
        $("#searchField").autocomplete('clear');
    },
    link: 'target.html?term=',
    minLength: 1
});

**Comment by powertronglobal** [comment]
you rock man. Thanks!!
