### ISSUE TITLE
display drop down button option

### ISSUE THREAD

**Issue by sygram** [commadelimited/autoComplete.js#8]
Hi there,

first of all thanks for sharing your great code.

It would also be nice if we could have the option of displaying a drop down arrow to the right of the component, so that the user can click to get all options, e.g. in case there are only a few. This will also give a "combobox" feeling to the user.

Thanks again.

Regards

**Comment by commadelimited** [comment]
Interesting idea. Thanks for your suggestion. I'll keep that in mind when I'm working on subsequent versions.

**Comment by sygram** [comment]
thanks for considering

**Comment by bernharduw** [comment]
+1 - this would be a nice feature!
