### ISSUE TITLE
Nested sources

### ISSUE THREAD

**Issue by Squishier** [commadelimited/autoComplete.js#9]
I have a data source of nested objects. I need to be able to search through this source and return results that are nested, and I'm hitting a wall. I was hoping you could help me out. Here's my JSON and the buildList function that I've edited:

JSON:
[
    {
        "label": "sitegroup1",
        "children": 
        [
            { 
               "label": "site1",
               "children": 
               [
                    {"label": "datasource1", "datasourceid":99},
                    {"label":"datasource2","datasourceid":13}
               ]
            }
        ]
   }
}

And buildList function:

buildItems = function($this, data, settings) {
        var str = [];
        $.each(data, function(index, value) {
            // are we working with objects or strings?
            if ($.isPlainObject(value)) {
                //if(value.datasourceid){
                    str.push('<li class="datasource" data-icon="myapp-charts"><a href="' + settings.link +'" data-transition="' + settings.transition + '"><div class="source" title="' + encodeURIComponent(value.value) + '">' + value.label + '</div></a></li>');
                //}else{
                //  str.push('<li class="sitesource" data-icon="myapp-arrow">' + value.label);
                //      if(value.children){
                //          str.push('<ul data-filter="true">');
                //          str.push(buildItems(value.children));
                //          str.push("</ul>");
                //      }
                //  str.push('</ul>');  
                //}
            } else {
                str.push('<li><a href="' + settings.link + encodeURIComponent(value) + '" data-transition="' + settings.transition + '">' + value + '</a></li>');
            }
        });
        $(settings.target).html(str.join('')).listview("refresh");

The commented out code is what I've done myself. If you could help me out here I'd be very grateful!

**Comment by commadelimited** [comment]
Squishier...

I'm happy to take a look at this, but it'll be easier if you can put together a quick demo for me to review.

**Comment by Squishier** [comment]
I'm having no luck at all with jsFiddle, and I have no web-hosting to speak of. I could send you a Drive link?

**Comment by commadelimited** [comment]
Google Drive I assume? You could ZIP it up and shoot me an email with the link.
